# Generated by Django 5.0.2 on 2024-03-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0002_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
