# Generated by Django 5.0.2 on 2024-03-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0003_nurse_experience_nurse_image_alter_nurse_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='image',
        ),
    ]
