# Generated by Django 5.0.2 on 2024-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0004_remove_nurse_experience_remove_nurse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
