# Generated by Django 5.0.2 on 2024-03-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0006_nurse_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
