# Generated by Django 5.0.2 on 2024-03-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0007_nurse_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='profile',
        ),
    ]
