# Generated by Django 5.0.2 on 2024-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0009_nurse_image_nurse_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
