# Generated by Django 5.0.2 on 2024-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0011_alter_nurse_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
