# Generated by Django 5.0.2 on 2024-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0012_nurse_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
