# Generated by Django 5.0.2 on 2024-04-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0013_alter_normaluser_profile_alter_nurse_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
