# Generated by Django 5.0.2 on 2024-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0003_deviceinformation_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinformation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
