# Generated by Django 5.0.2 on 2024-03-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0004_alter_deviceinformation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
