# Generated by Django 5.0.2 on 2024-03-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0006_alter_deviceinformation_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinformation',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
