# Generated by Django 5.0.2 on 2024-03-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0007_alter_deviceinformation_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinformation',
            name='status',
        ),
    ]
