# Generated by Django 5.0.2 on 2024-03-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0009_approveddevice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approveddevice',
            old_name='status',
            new_name='is_approved',
        ),
    ]
