# Generated by Django 5.0.2 on 2024-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0010_rename_status_approveddevice_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDeviceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('seller_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('product_image', models.FileField(upload_to='images/')),
                ('phone', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='deviceinformation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ApprovedDevice',
        ),
    ]
