# Generated by Django 5.0.2 on 2024-03-14 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0011_approveddeviceinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_devices.deviceinformation')),
            ],
        ),
        migrations.DeleteModel(
            name='ApprovedDeviceInformation',
        ),
    ]
