# Generated by Django 5.0.2 on 2024-03-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0012_approveddevice_delete_approveddeviceinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinformation',
            name='is_approved',
        ),
    ]
