# Generated by Django 5.0.2 on 2024-03-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0014_remove_approveddevice_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveddevice',
            name='device_id',
        ),
        migrations.AddField(
            model_name='approveddevice',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='approveddevice',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='approveddevice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AddField(
            model_name='approveddevice',
            name='product_image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='approveddevice',
            name='product_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='approveddevice',
            name='seller_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='approveddevice',
            name='uid',
            field=models.IntegerField(default=None),
        ),
    ]
