# Generated by Django 5.0.2 on 2024-03-14 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0015_remove_approveddevice_device_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedDevice',
        ),
        migrations.RemoveField(
            model_name='deviceinformation',
            name='uid',
        ),
        migrations.AddField(
            model_name='deviceinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
