# Generated by Django 5.0.2 on 2024-03-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0017_deviceinformation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinformation',
            name='product_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
