# Generated by Django 5.0.2 on 2024-03-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0018_alter_deviceinformation_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinformation',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
