# Generated by Django 5.1.4 on 2025-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_devices', '0019_alter_deviceinformation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinformation',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
