# Generated by Django 5.0.2 on 2024-03-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_nursebooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursebooking',
            old_name='Nurse',
            new_name='nurse',
        ),
    ]
