# Generated by Django 5.0.2 on 2024-03-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_rename_nurse_nursebooking_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursebooking',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
