# Generated by Django 5.1.4 on 2025-03-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_medicineorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcart',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Divicecart',
        ),
        migrations.DeleteModel(
            name='Medcart',
        ),
    ]
