# Generated by Django 5.1.4 on 2025-03-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_divicecart_medcart_delete_cartitem'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicines.medicine_inventory'),
        ),
        migrations.DeleteModel(
            name='MedicineOrder',
        ),
    ]
