# Generated by Django 5.1.4 on 2025-03-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_medicine_delete_medicineorder'),
        ('clinical_devices', '0022_alter_deviceinformation_quantity_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinical_devices.deviceinformation'),
        ),
    ]
